# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hibernate-demo
    username: root
    password: george1981
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

## Logging Configuration
#logging:
#  level:
#    org:
#      springframework: DEBUG
